# Generated by Django 5.0.1 on 2024-04-24 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('total_spaces', models.IntegerField()),
                ('available_spaces', models.IntegerField(default=models.IntegerField())),
                ('hourly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('daily_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField()),
                ('is_occupied', models.BooleanField(default='empty')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parking')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=100, null=True, unique=True)),
                ('booking_time', models.DateTimeField()),
                ('booking_duration', models.DurationField()),
                ('booking_status', models.BooleanField(default=False)),
                ('remarks', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.parkingslot')),
            ],
        ),
    ]
